name: Development Tests

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
  push:
    paths:
      - '.github/**'
      - 'test/CoolPropDevLoader/**'

concurrency:
  # Skip intermediate builds: all builds except for builds on the `master` branch
  # Cancel intermediate builds: only pull request builds
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test-coolprop-dev:
    timeout-minutes: 30
    strategy:
      matrix:
        julia_version:
          - '1.12'
        os:
          - ubuntu-latest
        julia_arch:
          - x64
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - uses: julia-actions/setup-julia@v3
      with:
        arch: ${{ matrix.julia_arch }}
        version: ${{ matrix.julia_version }}
    - uses: julia-actions/cache@v3

    - name: add CoolPropDevLoader
      shell: julia --color=yes --project=. {0}
      run: |
        using Pkg
        Pkg.develop(path="test/CoolPropDevLoader")

    - name: Compiling CoolProp
      shell: julia --color=yes --compiled-modules=no --project=test {0}
      run: |
        using Pkg
        Pkg.develop(path="test/CoolPropDevLoader")
        using CoolPropDevLoader
        CoolPropDevLoader.use_dev_library(CoolPropDevLoader.CompileCoolPropFromSourceforge())
        Pkg.add("Test")

    - uses: julia-actions/julia-runtest@v1